---
hero_image: images/drum-loop.png
theme: green
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Drumloop
description: Leer hoe je samples kunt gebruiken om je eigen drumloop te creëren.
original_url: https://codeclubprojects.org/en-GB/sonic-pi/drum-loop
interests: music
technologies: sonic-pi
site_areas: projects
hardware: ''
software: sonic-pi
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Inleiding
  - 
    title: Het intro
  - 
    title: De drumloop
    completion:
      - engaged
  - 
    title: Het outro
    completion:
      - internal
  - 
    title: 'Uitdaging: maak je eigen drumloop'
