---
hero_image: images/banner.png
theme: red
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
title: Drum Loop
description: Learn how to use samples to create your own drum loop.
original_url: https://codeclubprojects.org/en-GB/sonic-pi/drum-loop
interests: music/sound
technologies: ''
site_areas: codeclub, sonic-pi
steps:
- title: Introduction
- title: The intro
- title: The drum loop
- title: The outro
- title: 'Challenge: Create your own drum loop'

