---
hero_image: images/drum-loop.png
theme:  green
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Trommeloop
description: Lær at bruge samples i Sonic Pi til at lave din egen trommeloop.
original_url: https://codeclubprojects.org/en-GB/sonic-pi/drum-loop
interests: music
technologies: 'sonic-pi'
site_areas: projects
hardware: ''
software: 'sonic-pi'
version: 3
last_tested: 2017-01-01
steps:
- title: Introduktion
- title: Introen
- title: Trommeloopet
- title: Outroen
- title: 'Udfordring: Lav din egen trommeloop'
