---
hero_image: images/drum-loop.png
theme: green
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Loop de Bateria
description: Aprenda a usar samples (amostras) para criar seu próprio loop de bateria.
original_url: https://codeclubprojects.org/en-GB/sonic-pi/drum-loop
interests: music
technologies: 'sonic-pi'
site_areas: projects
hardware: ''
software: 'sonic-pi'
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Introdução
  - 
    title: A introdução
  - 
    title: O loop de bateria
  - 
    title: A conclusão
  - 
    title: 'Desafio: Crie seu próprio loop de bateria'
