---
hero_image: images/drum-loop.png
theme: green
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Bucle de batería
description: Aprende a utilizar muestras de audio para crear tu propio bucle de batería.
original_url: https://codeclubprojects.org/en-GB/sonic-pi/drum-loop
interests: music
technologies: sonic-pi
site_areas: projects
hardware: ''
software: sonic-pi
version: 3
last_tested: 2017-01-01
steps:
- title: Introducción
  completion: engaged
- title: La intro
- title: El bucle de batería
- title: El outro
  completion: internal
- title: 'Desafío: Crea tu propio bucle de batería'
