---
hero_image: images/drum-loop.png
theme: اخضر
duration: 0
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: حلقة الطبل (نغمة موسيقية)
description: تعلم كيفية استخدام العينات لإنشاء حلقة الطبل الخاصة بك.
original_url: https://codeclubprojects.org/en-GB/sonic-pi/drum-loop
interests: موسيقى
technologies: 'sonic-pi'
site_areas: codeclub, python
hardware: ''
software: 'sonic-pi'
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: المقدمة
  - 
    title: المقدمة
  - 
    title: حلقة الطبل
  - 
    title: المقدمة
  - 
    title: 'التحدي: أنشئ حلقة الطبل الخاصة بك'
